### ISSUE TITLE
Failure during gcc-linux64 didnt resume

### ISSUE THREAD

**Issue by jayvdb** [indygreg/python-build-standalone#21]
Brief internet problems caused a failure during finalisation of gcc-linux64, and restarting resulted in job starting at image-clang.
 
````console
gcc-linux64> make[8]: Leaving directory `/build/gcc-objdir/x86_64-unknown-linux-gnu/32/libsanitizer'
gcc-linux64> make[7]: Leaving directory `/build/gcc-objdir/x86_64-unknown-linux-gnu/32/libsanitizer'
gcc-linux64> make[6]: Leaving directory `/build/gcc-objdir/x86_64-unknown-linux-gnu/32/libsanitizer'
gcc-linux64> make[5]: Leaving directory `/build/gcc-objdir/x86_64-unknown-linux-gnu/libsanitizer'
gcc-linux64> make[4]: Leaving directory `/build/gcc-objdir/x86_64-unknown-linux-gnu/libsanitizer'
gcc-linux64> make[3]: Leaving directory `/build/gcc-objdir/x86_64-unknown-linux-gnu/libsanitizer'
gcc-linux64> make[2]: Leaving directory `/build/gcc-objdir/x86_64-unknown-linux-gnu/libsanitizer'
gcc-linux64> make[1]: Leaving directory `/build/gcc-objdir'
gcc-linux64> ~
gcc-linux64> copying container files to /home/jayvdb/projects/python/python-build-standalone/build/gcc-9.1.0-linux64.tar
Traceback (most recent call last):
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.7/http/client.py", line 1333, in getresponse
    response.begin()
  File "/usr/lib64/python3.7/http/client.py", line 305, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.7/http/client.py", line 266, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jayvdb/projects/python/python-build-standalone/cpython-unix/build.py", line 899, in <module>
    sys.exit(main())
  File "/home/jayvdb/projects/python/python-build-standalone/cpython-unix/build.py", line 752, in main
    build_gcc(client, get_image(client, ROOT, BUILD, "gcc"))
  File "/home/jayvdb/projects/python/python-build-standalone/cpython-unix/build.py", line 158, in build_gcc
    build_env.get_tools_archive(archive_path("gcc", "linux64"), "host")
  File "/usr/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/jayvdb/projects/python/python-build-standalone/pythonbuild/buildenv.py", line 201, in build_environment
    container.remove()
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/docker/models/containers.py", line 347, in remove
    return self.client.api.remove_container(self.id, **kwargs)
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/docker/api/container.py", line 994, in remove_container
    self._url("/containers/{0}", container), params=params
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/docker/api/client.py", line 238, in _delete
    return self.delete(url, **self._set_request_timeout(kwargs))
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/requests/sessions.py", line 615, in delete
    return self.request('DELETE', url, **kwargs)
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/jayvdb/projects/python/python-build-standalone/build/venv.linux/lib64/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
make: *** [Makefile:95: /home/jayvdb/projects/python/python-build-standalone/build/gcc-9.1.0-linux64.tar] Error 1
```
```console
~python-build-standalone> ./build-linux.py
Requirement already satisfied: certifi==2019.9.11 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 7)) (2019.9.11)
Requirement already satisfied: cffi==1.13.1 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 11)) (1.13.1)
Requirement already satisfied: chardet==3.0.4 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 43)) (3.0.4)
Requirement already satisfied: click==7.0 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 47)) (7.0)
Requirement already satisfied: docker==4.1.0 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 51)) (4.1.0)
Requirement already satisfied: idna==2.8 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 54)) (2.8)
Requirement already satisfied: jinja2==2.10.3 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 58)) (2.10.3)
Requirement already satisfied: markupsafe==1.1.1 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 61)) (1.1.1)
Requirement already satisfied: pip-tools==4.2.0 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 91)) (4.2.0)
Requirement already satisfied: pycparser==2.19 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 94)) (2.19)
Requirement already satisfied: requests==2.22.0 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 97)) (2.22.0)
Requirement already satisfied: six==1.12.0 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 101)) (1.12.0)
Requirement already satisfied: urllib3==1.25.6 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 105)) (1.25.6)
Requirement already satisfied: websocket-client==0.56.0 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 109)) (0.56.0)
Requirement already satisfied: zstandard==0.12.0 in ./build/venv.linux/lib/python3.7/site-packages (from -r /home/jayvdb/projects/python/python-build-standalone/requirements.txt (line 113)) (0.12.0)
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/jayvdb/projects/python/python-build-standalone/cpython-unix/build.py image-clang
image-clang> Step 1/9 : FROM debian@sha256:37103c15605251b2e35b70a3214af626a55cff39abbaadccd01ff828ee7005e0
```

**Comment by indygreg** [comment]
This is probably Python losing connection to the Docker daemon. Feels like a minor bug that can easily be worked around by rebuilding.

**Comment by indygreg** [comment]
I don't see anything actionable in this issue, so closing.
