### ISSUE TITLE
Windows 10 cpython-3.8 build fails with autoreconf

### ISSUE THREAD

**Issue by TanyRay** [indygreg/python-build-standalone#54]
I try to build `python.exe build-windows.py --python cpython-3.8 --sh C:\Soft\cygwin64\bin\sh.exe --profile static-noopt` and got the following exception:

`'.toreconf-2.69: unrecognized option '-
autoreconf-2.69: Try '/usr/bin/autoreconf-2.69 --help' for more information.
Traceback (most recent call last):
  File "build.py", line 2267, in <module>
    sys.exit(main())
  File "build.py", line 2241, in main
    build_libffi(
  File "build.py", line 1485, in build_libffi
    subprocess.run(args, env=env, check=True)
  File "C:\Soft\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\MyUser\\AppData\\Local\\Temp\\libffi-build-hxqnsout\\Python-3.8.3\\PCBuild\\prepare_libffi.bat', '-pdb', '-x64']' returned non-zero exit status 1.`

Could someone help? When I build cpython-3.7 everything is ok.

**Comment by Schamper** [comment]
This is because of how you've configured git to checkout newlines. The checkout is done with the "Windows Git" (which by default is configured to convert LF to CRLF on checkout), but the files are used within cygwin, which requires LF line endings. `core.autocrlf` should be set to either `false` or `input` to prevent git from converting the LF newlines to CRLF.
