### ISSUE TITLE
Unable to run -m pip on Windows

### ISSUE THREAD

**Issue by vrkosk** [indygreg/python-build-standalone#94]
This is similar to issue #85, which is marked as fixed. When I extract the 3.9.6 build and run pip with:

.\python.exe -m pip list

pip fails with an error:

```
Traceback (most recent call last):
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_internal\cli\main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_internal\cli\cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_internal\cli\parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_internal\configuration.py", line 21, in <module>
    from pip._internal.exceptions import (
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_internal\exceptions.py", line 8, in <module>
    from pip._vendor.requests.models import Request, Response
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_vendor\requests\__init__.py", line 43, in <module>
    from pip._vendor import urllib3
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_vendor\urllib3\__init__.py", line 11, in <module>
    from . import exceptions
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_vendor\urllib3\exceptions.py", line 3, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
  File "D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_vendor\urllib3\packages\__init__.py", line 3, in <module>
    from . import ssl_match_hostname
ImportError: cannot import name 'ssl_match_hostname' from partially initialized module 'pip._vendor.urllib3.packages' (most likely due to a circular import) (D:\work\villek\python\python-build-standalone\xyzzy\lib\site-packages\pip-21.1.3-py3.9.egg\pip\_vendor\urllib3\packages\__init__.py)
```

Most pip commands fail in the same place, e.g. -m pip install. Just running "-m pip --help" works.

Windows Server 2019. I've tried 3.9.6, 3.9.0 and 3.8.11 builds of cpython-*-x86_64-pc-windows-msvc-shared-pgo-*.tar.zst, and all fail in the same way.

Workaround is the same as mentioned in issue #85, which is: download get-pip.py from https://pip.pypa.io/en/stable/installation/ and:

.\python.exe get-pip.py

After that, works fine:

```
.\python.exe -m pip list
Package    Version
---------- -------
pip        21.2.4
setuptools 58.2.0
wheel      0.37.0
```

I don't know whether it makes a difference, but the PC is behind a proxy server. Using --proxy makes no difference to the list command anyway. The workaround is OK for my use case.

**Comment by indygreg** [comment]
The purported fix is not yet in a released version of python-build-standalone. Could you please try downloading one of the artifacts from CI and see if you can still reproduce?
